version: 2.1

commands:
  cached-checkout:
      description: "checkout with caching"
      steps:
        - restore_cache:
            name: Restore Git Cache
            keys:
              - git-{{ .Branch }}-{{ .Revision }}
              - git-{{ .Branch }}-
              - git-
        - checkout:
            name: Check Out Code
        - run:
            name: Fetch from Git
            command: |
              git fetch origin
              git config user.name 'CircleCI Automated Commit'
              git config user.email 'github@raccoonfink.com'
        - save_cache:
            name: Save Git Cache
            key: git-{{ .Branch }}-{{ .Revision }}
            paths:
              - ".git"
  generate-changelog:
      steps:
        - run:
            name: Generate Change Log
            command: npm run changelog
  cached-npm-install:
      description: run "npm install", updating cache
      steps:
        - restore_cache:
            name: Restore Package Cache
            keys:
              - npm-packages-{{ .Branch }}-{{ checksum "package-lock.json" }}
              - npm-packages-{{ .Branch }}
              - npm-packages-
        - run:
            name: Install Node Dependencies
            command: npm --prefer-offline --no-progress install
        - save_cache:
            name: Save Package Cache
            key: npm-packages-{{ .Branch }}-{{ checksum "package-lock.json" }}
            paths:
              - node_modules/

jobs:
  run-tests:
      docker:
        - image: circleci/node:10
      steps:
        - checkout
        - cached-npm-install
        - run:
            name: Run Tests
            command: npm --prefer-offline --no-progress run test
  merge-master:
      docker:
        - image: circleci/node:10
      steps:
        - cached-checkout
        - run:
            name: Merge Develop to Master
            command: |
              git pull --ff-only
              git checkout master
              git pull --ff-only
              git merge -m 'automated merge from develop -> master' --log develop
        - cached-npm-install
        - run:
            name: Build Artifacts
            command: npm --prefer-offline --no-progress run build
        - generate-changelog
        - run:
            name: Commit and Push Updated Artifacts
            command: |
              git add -A
              if [ `git diff HEAD | wc -l` -gt 0 ]; then
                echo "code detected; committing updated dist/ as part of the merge"
                git commit --amend -m 'automated merge from develop -> master'
              fi
              git push

workflows:
  run-tests:
    jobs:
      - run-tests:
          filters:
            branches:
              ignore:
                - develop
  run-tests-and-deploy:
    jobs:
      - run-tests:
          filters:
            branches:
              only:
                - develop
      - merge-master:
          requires:
            - run-tests
          filters:
            branches:
              only:
                - develop

